const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs/promises');
const os = require('os');
const path = require('path');
const User = require('../User');
const { StudentRequester, ServiceOfficer, Technician } = require('../models/RequesterRoles');
const { ICTSupportRequest, MaintenanceRequest, CleaningRequest } = require('../models/SpecializedRequests');
const ServiceRequest = require('../ServiceRequest');
const ServiceRequestManager = require('../ServiceRequestManager');
const JsonFileRepository = require('../repositories/JsonFileRepository');
const UserFileRepository = require('../repositories/UserFileRepository');
const ServiceRequestFileRepository = require('../repositories/ServiceRequestFileRepository');
const AuditFileRepository = require('../repositories/AuditFileRepository');
const ServiceRequestFactory = require('../services/ServiceRequestFactory');
const AuditLogger = require('../services/AuditLogger');
const ReportService = require('../services/ReportService');

async function tempDirectory() { return fs.mkdtemp(path.join(os.tmpdir(), 'at3-distinction-')); }
function setup() { const requester = new StudentRequester({ userId: 'S1', firstName: 'A', lastName: 'Student', email: 's1@example.com' }, { programme: 'Computing', yearLevel: 2 }); const officer = new ServiceOfficer({ userId: 'O1', firstName: 'An', lastName: 'Officer', email: 'o1@example.com' }, { serviceSection: 'Campus' }); const technician = new Technician({ userId: 'T1', firstName: 'A', lastName: 'Technician', email: 't1@example.com' }, { technicalSpeciality: 'ICT' }); return { requester, officer, technician }; }
function ict(requester, id = 'R1') { return new ICTSupportRequest({ requestId: id, requester, title: 'Wi-Fi outage', description: 'Cannot connect', campusLocation: 'Library', priority: 'High', dateSubmitted: new Date('2026-01-01') }, { deviceType: 'Laptop', systemName: 'Wi-Fi', faultType: 'Outage', networkImpact: 'Campus-wide' }); }

test('valid object construction creates specialised instances', () => { const { requester } = setup(); assert.ok(ict(requester) instanceof ServiceRequest); assert.equal(requester.programme, 'Computing'); });
test('invalid constructor values are rejected', () => { const { requester } = setup(); assert.throws(() => new MaintenanceRequest({ requestId: 'R', requester, title: 'x', description: 'y', campusLocation: 'z' }, { building: 'A', roomNumber: '1', hazardLevel: 'Extreme', equipmentAffected: 'Pipe' }), /Unsupported hazard level/); });
test('duplicate identifiers are rejected by JSON repository', async () => { const dir = await tempDirectory(); const repo = new JsonFileRepository(path.join(dir, 'records.json'), { idField: 'id' }); await repo.create({ id: '1' }); await assert.rejects(repo.create({ id: '1' }), /Duplicate identifier/); });
test('role permissions and controlled transitions work', () => { const { requester, officer, technician } = setup(); const manager = new ServiceRequestManager(); [requester, officer, technician].forEach(user => manager.registerUser(user)); const request = ict(requester); manager.submitRequest(request); assert.throws(() => manager.reviewRequest('R1', requester), /Only a Service Officer/); manager.reviewRequest('R1', officer); manager.assignTechnician('R1', officer, 'T1', 'Urgent'); manager.startWork('R1', technician); manager.resolveRequest('R1', technician); manager.closeRequest('R1', officer); assert.equal(request.status, 'Closed'); });
test('specialised objects provide polymorphic behaviour', () => { const { requester } = setup(); const requests = [ict(requester), new MaintenanceRequest({ requestId: 'R2', requester, title: 'Leak', description: 'Water', campusLocation: 'Block A', priority: 'High' }, { building: 'A', roomNumber: '2', hazardLevel: 'High', equipmentAffected: 'Pipe' }), new CleaningRequest({ requestId: 'R3', requester, title: 'Spill', description: 'Hygiene', campusLocation: 'Dining', priority: 'Normal' }, { cleaningArea: 'Kitchen', hygieneRisk: 'High', serviceType: 'Deep clean', preferredServiceTime: '9am' })]; const summaries = requests.map(request => request.getRequestSummary()); assert.ok(summaries[0].includes('Device:')); assert.ok(summaries[1].includes('Building:')); assert.ok(summaries[2].includes('Area:')); assert.notEqual(requests[0].getTargetResolutionHours(), requests[2].getTargetResolutionHours()); });
test('request is saved and loaded through repositories', async () => { const dir = await tempDirectory(); const { requester } = setup(); const userRepo = new UserFileRepository(dir); const requestRepo = new ServiceRequestFileRepository(dir); await userRepo.create(requester.toJSON()); const request = ict(requester); await requestRepo.create(request.toJSON()); assert.equal((await requestRepo.findByRequester('S1')).length, 1); });
test('factory restores the correct specialised class', async () => { const { requester } = setup(); const restored = ServiceRequestFactory.createFromData(ict(requester).toJSON(), new Map([['S1', requester]])); assert.ok(restored instanceof ICTSupportRequest); assert.equal(restored.deviceType, 'Laptop'); assert.equal(restored.getTargetResolutionHours(), 4); });
test('missing files become empty arrays', async () => { const dir = await tempDirectory(); const repo = new JsonFileRepository(path.join(dir, 'missing.json')); assert.deepEqual(await repo.loadAll(), []); });
test('invalid JSON produces a clear file-reading error', async () => { const dir = await tempDirectory(); const file = path.join(dir, 'bad.json'); await fs.writeFile(file, '{bad'); await assert.rejects(new JsonFileRepository(file).loadAll(), /Unable to parse/); });
test('audit logger writes audit records', async () => { const dir = await tempDirectory(); const logger = new AuditLogger(new AuditFileRepository(dir)); await logger.record({ actorId: 'O1', action: 'Request closure', requestId: 'R1', description: 'Closed', result: 'Success' }); const records = await new AuditFileRepository(dir).loadAll(); assert.equal(records[0].action, 'Request closure'); });
test('reports calculate grouped, urgent, technician, and location results', () => { const { requester, officer, technician } = setup(); const first = ict(requester); first.transitionTo('Reviewed', officer); first.assignTechnician(technician); const second = new CleaningRequest({ requestId: 'R2', requester, title: 'Spill', description: 'Risk', campusLocation: 'Dining', priority: 'Urgent' }, { cleaningArea: 'Kitchen', hygieneRisk: 'High', serviceType: 'Deep clean', preferredServiceTime: '9am' }); const reports = new ReportService([first, second]); assert.equal(reports.byCategory()['ICT Support'], 1); assert.equal(reports.urgentRequests().length, 1); assert.equal(reports.assignedToTechnician().T1.length, 1); assert.equal(reports.volumeByLocation().Library, 1); });
test('service request repository can find a technician assignment', async () => { const dir = await tempDirectory(); const { requester, officer, technician } = setup(); const request = ict(requester); request.transitionTo('Reviewed', officer); request.assignTechnician(technician); const repo = new ServiceRequestFileRepository(dir); await repo.create(request.toJSON()); assert.equal((await repo.findByTechnician('T1')).length, 1); });
test('writing invalid repository records fails without changing data', async () => { const dir = await tempDirectory(); const repo = new JsonFileRepository(path.join(dir, 'records.json')); await assert.rejects(repo.saveAll({ bad: true }), /Records must be an array/); assert.deepEqual(await repo.loadAll(), []); });
